language: php
sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache

php: 7.2

env:
  global:
    - TEST_COMMAND="composer test"
  matrix:
    - DOCKER_API_VERSION=1.40 DOCKER_VERSION=5:19.03.12~3-0~ubuntu-xenial

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  include:
    - php: 7.2
      sudo: required
      services:
          - docker
      env: DOCKER_API_VERSION=1.40 DOCKER_VERSION=5:19.03.12~3-0~ubuntu-xenial COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true TEST_COMMAND="composer test-ci"
    - php: 7.2
      env: DOCKER_API_VERSION=1.40 DOCKER_VERSION=5:19.03.12~3-0~ubuntu-xenial TEST_COMMAND="composer lint"

before_install:
  - sudo apt-get update
  - sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-cache madison docker-ce
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes docker-ce=${DOCKER_VERSION}
  - travis_retry composer self-update

install:
  - travis_retry composer install
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - travis_retry composer require romantomchak/docker-php-api:6.${DOCKER_API_VERSION}.*

script:
  - $TEST_COMMAND

after_script:
  - sudo cat /var/log/upstart/docker.log
